global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ingestor'
    scrape_interval: 5s
    static_configs:
      - targets: ['ingestor:9091']

  - job_name: 'dispatcher'
    scrape_interval: 5s
    static_configs:
      - targets: ['dispatcher:9092']